import { useState } from "react";
import { ArrowRight, ChartActivity, CloudArrowUp, CommandLine, DocumentText, Eye, LockClosedSolid, ShieldCheck, SquaresPlus, UserGroup } from "@medusajs/icons";
import { FaGithub } from "react-icons/fa";
import canvasPreview from "../../assets/images/image2.png";

const features = [[SquaresPlus, "Canvas visuel", "Composez conteneurs, réseaux, volumes et passerelles par glisser-déposer — un schéma d’architecture vivant."], [DocumentText, "Plan avant déploiement", "Visualisez le diff exact : créations, mises à jour et suppressions, avant toute action sur Docker."], [UserGroup, "Délégation par rôle", "Owner, Operator, Viewer : donnez le bon niveau d’accès sans partager les clés du cluster."], [Eye, "Journal d’audit", "Chaque déploiement, suppression ou modification sensible est tracée et consultable."], [ChartActivity, "Auto-scaling", "Ajustez les replicas selon le CPU réellement observé, sans script cron externe à maintenir."], [LockClosedSolid, "Secrets chiffrés", "Vos identifiants ne transitent jamais en clair et ne sont jamais déposés dans un label Docker."]];

export function ProductOverview() { return <section className="hb-section hb-split" id="how"><div className="hb-wrap hb-split-grid"><div><span className="hb-eyebrow">Une interface pour opérer</span><h2>Dessinez votre infrastructure avant de la déployer.</h2><p>Le canvas Hullbay relie conteneurs, réseaux, volumes et passerelles. Vous composez une vue fidèle de votre projet, sans vous perdre dans un fichier YAML.</p><a className="hb-text-link" href="#features">Découvrir les fonctionnalités <ArrowRight /></a></div><figure className="hb-product-preview"><div className="hb-preview-bar"><span /><span /><span /><b>Console Hullbay · Canvas</b></div><img src={canvasPreview} alt="Canvas réel Hullbay montrant les conteneurs, réseaux, volumes et passerelles d’un projet" /><figcaption>Une vue réelle du canvas de déploiement Hullbay.</figcaption></figure></div></section> }
export function Workflow() { return <section className="hb-section hb-workflow"><div className="hb-wrap"><div className="hb-section-head"><span className="hb-eyebrow">Un chemin sans surprise</span><h2>Du serveur vierge au déploiement maîtrisé.</h2><p>Hullbay vous accompagne à chaque étape, sans vous enfermer dans une plateforme cloud.</p></div><div className="hb-step-grid"><article><span>01</span><CommandLine /><h3>Initialisez votre serveur</h3><p>Une commande installe Docker si nécessaire, prépare Hullbay et initialise votre Swarm.</p></article><article><span>02</span><SquaresPlus /><h3>Composez votre infrastructure</h3><p>Assemblez services, réseaux, volumes et passerelles dans un canvas visuel validé en temps réel.</p></article><article><span>03</span><ShieldCheck /><h3>Vérifiez, puis déployez</h3><p>Relisez le plan de changements avant application. Vos opérations restent auditées et sous contrôle.</p></article></div></div></section> }
export function Features() { return <section className="hb-section" id="features"><div className="hb-wrap"><div className="hb-section-head"><span className="hb-eyebrow">Fonctionnalités</span><h2>Tout ce qu’il faut pour déléguer les opérations, sans déléguer le contrôle.</h2></div><div className="hb-feature-grid">{features.map(([Icon, title, text]) => <article className="hb-feature" key={title}><span className="hb-feature-icon"><Icon /></span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section> }
export function Install() { const [copied, setCopied] = useState(false); const command = "curl -fsSL https://raw.githubusercontent.com/fotetsa/hullbay/master/install.sh | sudo bash"; const copy = async () => { try { await navigator.clipboard.writeText(command); setCopied(true); setTimeout(() => setCopied(false), 1600) } catch {/* Clipboard unavailable */ } }; return <section className="hb-section" id="install"><div className="hb-wrap hb-install-grid"><div><span className="hb-eyebrow">Démarrage</span><h2>Une commande. Un serveur frais. C’est prêt.</h2><p>Installe Docker, initialise le Swarm, démarre la console. Idempotent — relançable sans rien casser.</p></div><div className="hb-terminal"><div><span className="term-dots"><i /><i /><i /></span><button onClick={copy}>{copied ? "Copié ✓" : <><CloudArrowUp /> Copier</>}</button></div><code><b>$</b> {command}</code></div></div></section> }
export function Security() { return <section className="hb-section hb-security"><div className="hb-wrap hb-security-grid"><div><span className="hb-eyebrow">Conçu pour l’infrastructure</span><h2>Le contrôle ne devrait pas exiger de compromis sur la sécurité.</h2><p>Hullbay sépare les rôles, conserve un journal d’audit et interpose un proxy entre l’API et le socket Docker.</p><a className="hb-text-link" href="#security/security-overview">Explorer la sécurité <ArrowRight /></a></div><div className="hb-security-card"><div><span className="hb-security-icon"><ShieldCheck /></span><span><b>Accès filtré</b><small>Le proxy Docker limite la surface d’attaque.</small></span></div><div><span className="hb-security-icon"><LockClosedSolid /></span><span><b>Secrets chiffrés</b><small>Les données sensibles restent privées.</small></span></div><div><span className="hb-security-icon"><Eye /></span><span><b>Traçabilité</b><small>Les opérations importantes restent visibles.</small></span></div></div></div></section> }
export function FinalCta() { return <section className="hb-final"><div className="hb-wrap"><div><span className="hb-eyebrow">Open source · MIT</span><h2>Prêt à reprendre le contrôle de votre cluster ?</h2><p>Installez Hullbay sur votre serveur, ou aidez-nous à bâtir une meilleure manière de piloter Docker Swarm.</p><div className="hb-final-actions"><a className="hb-button hb-primary" href="#install">Installer Hullbay <ArrowRight /></a><a className="hb-button hb-final-secondary" href="https://github.com/Fotetsa/Hullbay" target="_blank" rel="noreferrer"><FaGithub />Contribuer sur GitHub</a></div></div></div></section> }
